/**
 * The win sequence's sound: one four-note arpeggio, and one note per bounce.
 *
 * Synthesised, no sample files — the whole sound design is oscillators and
 * envelopes. Zero bytes to download, zero licensing questions, and mapping
 * pitch and brightness to impact speed is free. See docs/07-architecture.md.
 *
 * The notes are chosen by the pure functions at the top of this file and made
 * audible by the class at the bottom. That split is not decoration: WebAudio
 * cannot be run under `node --test`, and the part worth testing — that the
 * scale ascends, that nothing can land off it, that a dying card is quieter
 * than a hard bounce — is all arithmetic.
 *
 * This is the win sequence only. The card-movement and foundation sounds from
 * docs/07 are milestone 3, and share nothing with this but the idea.
 */

/**
 * C D E G A. Pentatonic because no two notes in it can clash: the rhythm is
 * generated by the physics and is different every game, so whatever the
 * cascade produces, it cannot sound wrong.
 */
const PENTATONIC = [0, 2, 4, 7, 9];

/** C4. Low enough to stay under the arpeggio, high enough to cut through. */
const ROOT_HZ = 261.63;

/** Roughly two octaves of the scale, which is ten degrees of it. */
const CASCADE_DEGREES = 2 * PENTATONIC.length;

/**
 * How far a single card's own bounces walk up the scale. Three degrees is
 * enough to hear a card arpeggiating as it dies without it wandering out of
 * the band the cascade has reached.
 */
const BOUNCE_SPREAD = 3;

/** The loudest bounce we expect, px/s. Impacts past this are simply the loudest. */
const LOUD_IMPACT = 1400;

const MIN_LEVEL = 0.12;
const MAX_LEVEL = 1;

/** Lowpass sweep: a hard bounce is brighter as well as louder. */
const DARK_HZ = 700;
const BRIGHT_HZ = 5200;

/** Degree `n` of the scale, in hertz. Degrees past the fifth wrap an octave up. */
export function scaleNote(degree: number): number {
  const step = Math.max(0, Math.round(degree));
  const semitones =
    (PENTATONIC[step % PENTATONIC.length] as number) +
    12 * Math.floor(step / PENTATONIC.length);
  return ROOT_HZ * Math.pow(2, semitones / 12);
}

/**
 * The note a bounce plays: the scale ascends across the cascade, and a card's
 * own successive bounces climb a little way further. `progress` is how far
 * through the cascade we are, `bounce` is which bounce this is for that card.
 */
export function bounceNote(progress: number, bounce: number): number {
  const base = Math.floor(clamp01(progress) * CASCADE_DEGREES);
  return scaleNote(base + (Math.max(0, bounce - 1) % BOUNCE_SPREAD));
}

/** Velocity mapping: a hard bounce is loud, a dying card ticks. */
export function bounceLevel(impact: number): number {
  return MIN_LEVEL + clamp01(impact / LOUD_IMPACT) * (MAX_LEVEL - MIN_LEVEL);
}

/** …and bright. The same mapping, applied to a lowpass rather than a gain. */
export function bounceCutoff(impact: number): number {
  return DARK_HZ + clamp01(impact / LOUD_IMPACT) * (BRIGHT_HZ - DARK_HZ);
}

/**
 * The only musical phrase in the entire product: C E G C, in time with the
 * foundation pulses. Stage 3 plays it inverted, which is what "resolving"
 * means here.
 */
export const ARPEGGIO_DEGREES = [0, 2, 3, 5];

function clamp01(value: number): number {
  return Math.min(1, Math.max(0, value));
}

/** Simultaneous notes. Past this the end of the cascade turns to mud. */
const VOICE_CAP = 8;

/** Gaps between the arpeggio's notes — the same 90ms as the foundation pulses. */
const ARPEGGIO_GAP_S = 0.09;

/** An instant gain change clicks; every level move is a ramp. */
const MUTE_RAMP_S = 0.04;

/** Skipping releases the voices rather than stopping them dead. */
const RELEASE_S = 0.12;

const MASTER_LEVEL = 0.5;
const BOUNCE_LEVEL = 0.22;
const ARPEGGIO_LEVEL = 0.16;
const THUMP_LEVEL = 0.18;

/** Voices are held in start order, so the cap steals from the front. */
interface Voice {
  gain: GainNode;
  stop: (at: number) => void;
}

/**
 * The WebAudio graph. Created lazily on the gesture that starts the sequence —
 * browsers block a context created any other way, and building one on page
 * load is a battery cost for a visit that never makes a sound.
 *
 * Every method is safe to call when there is no context, no WebAudio, or no
 * permission to make noise. Silence is a fine outcome; an exception thrown out
 * of a celebration is not.
 */
export class WinAudio {
  #ctx: AudioContext | null = null;
  #master: GainNode | null = null;
  #voices: Voice[] = [];
  #muted: boolean;
  #failed = false;

  constructor(muted = false) {
    this.#muted = muted;
  }

  /**
   * Open the context. Called from the move that won the game, which is the
   * user gesture the autoplay policy wants; without one the context stays
   * suspended and every note below is a no-op.
   */
  start(): void {
    const ctx = this.#context();
    if (ctx !== null && ctx.state === "suspended") void ctx.resume();
  }

  set muted(muted: boolean) {
    this.#muted = muted;
    const ctx = this.#ctx;
    const master = this.#master;
    if (ctx === null || master === null) return;
    master.gain.cancelScheduledValues(ctx.currentTime);
    master.gain.setTargetAtTime(
      muted ? 0 : MASTER_LEVEL,
      ctx.currentTime,
      MUTE_RAMP_S / 3,
    );
  }

  /** Ascending for Stage 1, descending for Stage 3. */
  arpeggio(descending = false): void {
    const ctx = this.#context();
    if (ctx === null) return;
    const degrees = descending
      ? [...ARPEGGIO_DEGREES].reverse()
      : ARPEGGIO_DEGREES;
    degrees.forEach((degree, i) => {
      this.#tone({
        frequency: scaleNote(degree + PENTATONIC.length),
        level: ARPEGGIO_LEVEL,
        cutoff: 3200,
        decay: 0.9,
        at: ctx.currentTime + i * ARPEGGIO_GAP_S,
        type: "sine",
      });
    });
  }

  /**
   * One bounce. `first` adds the soft sub-bass thump under a card's first
   * contact — heavily low-passed, so it is felt as weight rather than heard as
   * a note.
   */
  bounce(impact: number, progress: number, bounce: number): void {
    const ctx = this.#context();
    if (ctx === null) return;
    const level = bounceLevel(impact);
    this.#tone({
      frequency: bounceNote(progress, bounce),
      level: BOUNCE_LEVEL * level,
      cutoff: bounceCutoff(impact),
      decay: 0.18 + 0.3 * level,
      at: ctx.currentTime,
      type: "triangle",
    });
    if (bounce === 1) {
      this.#tone({
        frequency: 55,
        level: THUMP_LEVEL * level,
        cutoff: 120,
        decay: 0.22,
        at: ctx.currentTime,
        type: "sine",
      });
    }
  }

  /** Let everything ring off over 120ms rather than cutting it dead. */
  release(): void {
    const ctx = this.#ctx;
    if (ctx === null) return;
    const at = ctx.currentTime;
    for (const voice of this.#voices) {
      voice.gain.gain.cancelScheduledValues(at);
      voice.gain.gain.setTargetAtTime(0.0001, at, RELEASE_S / 3);
      voice.stop(at + RELEASE_S);
    }
    this.#voices = [];
  }

  close(): void {
    const ctx = this.#ctx;
    this.#ctx = null;
    this.#master = null;
    this.#voices = [];
    if (ctx !== null) void ctx.close().catch(() => {});
  }

  #context(): AudioContext | null {
    if (this.#ctx !== null) return this.#ctx;
    if (this.#failed || this.#muted) return null;
    if (typeof AudioContext === "undefined") {
      this.#failed = true;
      return null;
    }
    try {
      const ctx = new AudioContext();
      const master = ctx.createGain();
      master.gain.value = MASTER_LEVEL;
      master.connect(ctx.destination);
      this.#ctx = ctx;
      this.#master = master;
      return ctx;
    } catch {
      // No WebAudio, or the browser refused one. The sequence is still a
      // sequence; it is just a silent one.
      this.#failed = true;
      return null;
    }
  }

  /** One oscillator through one filter through one envelope. That is the whole instrument. */
  #tone(spec: {
    frequency: number;
    level: number;
    cutoff: number;
    decay: number;
    at: number;
    type: OscillatorType;
  }): void {
    const ctx = this.#ctx;
    const master = this.#master;
    if (ctx === null || master === null) return;
    this.#reap(spec.at);

    const osc = ctx.createOscillator();
    osc.type = spec.type;
    osc.frequency.value = spec.frequency;

    const filter = ctx.createBiquadFilter();
    filter.type = "lowpass";
    filter.frequency.value = spec.cutoff;
    filter.Q.value = 0.7;

    const gain = ctx.createGain();
    // 4ms of attack: fast enough to read as a hit, slow enough not to click.
    gain.gain.setValueAtTime(0.0001, spec.at);
    gain.gain.exponentialRampToValueAtTime(
      Math.max(0.0002, spec.level),
      spec.at + 0.004,
    );
    gain.gain.exponentialRampToValueAtTime(0.0001, spec.at + spec.decay);

    osc.connect(filter).connect(gain).connect(master);
    osc.start(spec.at);
    osc.stop(spec.at + spec.decay + 0.05);

    const voice: Voice = {
      gain,
      stop: (at) => {
        try {
          osc.stop(at);
        } catch {
          // Already stopped. Nothing to do and nothing to report.
        }
      },
    };
    osc.addEventListener("ended", () => {
      this.#voices = this.#voices.filter((v) => v !== voice);
    });
    this.#voices.push(voice);
  }

  /** Voice cap, oldest stolen. */
  #reap(now: number): void {
    while (this.#voices.length >= VOICE_CAP) {
      const oldest = this.#voices.shift();
      if (oldest === undefined) return;
      oldest.gain.gain.cancelScheduledValues(now);
      oldest.gain.gain.setTargetAtTime(0.0001, now, 0.01);
      oldest.stop(now + 0.04);
    }
  }
}
