import { RANK_COUNT } from "../engine/index.ts";

/**
 * Every sound the product makes: a card sliding, a card going home, and the
 * win sequence's arpeggio and pentatonic bounces.
 *
 * Synthesised, no sample files — the whole sound design is oscillators,
 * filtered noise bursts and envelopes. Zero bytes to download, zero licensing
 * questions, and mapping pitch and brightness to speed is free. See
 * docs/07-architecture.md.
 *
 * One class, because there is one `AudioContext`, one master gain and
 * therefore one mute. A second context is a second audio thread on a phone
 * for no gain, and a mute that only silenced half the product would be a bug
 * waiting to be filed.
 *
 * The notes are chosen by the pure functions at the top of this file and made
 * audible by the class at the bottom. That split is not decoration: WebAudio
 * cannot be run under `node --test`, and the part worth testing — that the
 * scale ascends, that nothing can land off it, that a dying card is quieter
 * than a hard bounce, that two moves running never make the same noise — is
 * all arithmetic.
 */

/**
 * C D E G A. Pentatonic because no two notes in it can clash: the rhythm is
 * generated by the physics and is different every game, so whatever the
 * cascade produces, it cannot sound wrong.
 */
const PENTATONIC = [0, 2, 4, 7, 9];

/** C4. Low enough to stay under the arpeggio, high enough to cut through. */
const ROOT_HZ = 261.63;

/** Roughly two octaves of the scale, which is ten degrees of it. */
const CASCADE_DEGREES = 2 * PENTATONIC.length;

/**
 * How far a single card's own bounces walk up the scale. Three degrees is
 * enough to hear a card arpeggiating as it dies without it wandering out of
 * the band the cascade has reached.
 */
const BOUNCE_SPREAD = 3;

/** The loudest bounce we expect, px/s. Impacts past this are simply the loudest. */
const LOUD_IMPACT = 1400;

const MIN_LEVEL = 0.12;
const MAX_LEVEL = 1;

/** Lowpass sweep: a hard bounce is brighter as well as louder. */
const DARK_HZ = 700;
const BRIGHT_HZ = 5200;

/** Degree `n` of the scale, in hertz. Degrees past the fifth wrap an octave up. */
export function scaleNote(degree: number): number {
  const step = Math.max(0, Math.round(degree));
  const semitones =
    (PENTATONIC[step % PENTATONIC.length] as number) +
    12 * Math.floor(step / PENTATONIC.length);
  return ROOT_HZ * Math.pow(2, semitones / 12);
}

/**
 * The note a bounce plays: the scale ascends across the cascade, and a card's
 * own successive bounces climb a little way further. `progress` is how far
 * through the cascade we are, `bounce` is which bounce this is for that card.
 */
export function bounceNote(progress: number, bounce: number): number {
  const base = Math.floor(clamp01(progress) * CASCADE_DEGREES);
  return scaleNote(base + (Math.max(0, bounce - 1) % BOUNCE_SPREAD));
}

/** Velocity mapping: a hard bounce is loud, a dying card ticks. */
export function bounceLevel(impact: number): number {
  return MIN_LEVEL + clamp01(impact / LOUD_IMPACT) * (MAX_LEVEL - MIN_LEVEL);
}

/** …and bright. The same mapping, applied to a lowpass rather than a gain. */
export function bounceCutoff(impact: number): number {
  return DARK_HZ + clamp01(impact / LOUD_IMPACT) * (BRIGHT_HZ - DARK_HZ);
}

/**
 * The only musical phrase in the entire product: C E G C, in time with the
 * foundation pulses. Stage 3 plays it inverted, which is what "resolving"
 * means here.
 */
export const ARPEGGIO_DEGREES = [0, 2, 3, 5];

/** Card movement: a band of noise around here, 25ms of it. */
const MOVE_HZ = 2400;

/** How far either side of that a single move may land. */
const MOVE_SPREAD = 0.14;

/**
 * Seven steps through the band, deliberately out of order. Repeated moves are
 * what make a card game sound like a machine gun, and a *rising* sequence
 * would only trade that for a scale nobody asked for. Seven is coprime with
 * every rhythm a player produces, so the cycle never locks to one.
 */
const MOVE_STEPS = [0, 0.7, -0.4, 1, -1, 0.35, -0.75];

/** The centre of the `n`th card-movement burst. Never twice the same in a row. */
export function moveCutoff(n: number): number {
  const step = MOVE_STEPS[
    Math.abs(Math.trunc(n)) % MOVE_STEPS.length
  ] as number;
  return MOVE_HZ * (1 + step * MOVE_SPREAD);
}

/**
 * A card going home, as a note: the thirteen ranks spread over exactly one
 * octave of the same pentatonic the cascade is in, so a foundation being
 * built is an ascending line and the two sounds can never clash. An Ace is C5
 * and a King is C6.
 */
export function homeNote(rank: number): number {
  const clamped = Math.min(RANK_COUNT - 1, Math.max(0, Math.round(rank)));
  const degree = Math.round((clamped / (RANK_COUNT - 1)) * PENTATONIC.length);
  return scaleNote(degree + PENTATONIC.length);
}

function clamp01(value: number): number {
  return Math.min(1, Math.max(0, value));
}

/** Simultaneous notes. Past this the end of the cascade turns to mud. */
const VOICE_CAP = 8;

/** Gaps between the arpeggio's notes — the same 90ms as the foundation pulses. */
const ARPEGGIO_GAP_S = 0.09;

/** An instant gain change clicks; every level move is a ramp. */
const MUTE_RAMP_S = 0.04;

/** Skipping releases the voices rather than stopping them dead. */
const RELEASE_S = 0.12;

const MASTER_LEVEL = 0.5;
const BOUNCE_LEVEL = 0.22;
const ARPEGGIO_LEVEL = 0.16;
const THUMP_LEVEL = 0.18;

/** Subtle, per docs/07. A card that announced itself would be unbearable by move fifty. */
const MOVE_LEVEL = 0.12;
const MOVE_DECAY_S = 0.025;
const HOME_LEVEL = 0.1;
const HOME_DECAY_S = 0.5;

/** A quarter second of white noise, made once and re-read for every burst. */
const NOISE_S = 0.25;

/** Voices are held in start order, so the cap steals from the front. */
interface Voice {
  gain: GainNode;
  stop: (at: number) => void;
}

/**
 * The WebAudio graph. Created lazily on the first gesture that makes a sound —
 * browsers block a context created any other way, and building one on page
 * load is a battery cost for a visit that never makes one.
 *
 * That laziness is also why the deal is silent: it runs on page load, before
 * any gesture, so there is no context for it to play through. Which is the
 * right answer anyway — twenty-eight bursts in six hundred milliseconds is a
 * riffle, not a sound design.
 *
 * Every method is safe to call when there is no context, no WebAudio, or no
 * permission to make noise. Silence is a fine outcome; an exception thrown out
 * of a celebration is not.
 */
export class Sound {
  #ctx: AudioContext | null = null;
  #master: GainNode | null = null;
  #noise: AudioBuffer | null = null;
  #voices: Voice[] = [];
  #moves = 0;
  #muted: boolean;
  #failed = false;

  constructor(muted = false) {
    this.#muted = muted;
  }

  /**
   * Open the context. Called from the gesture that played a move, which is
   * the user gesture the autoplay policy wants; without one the context stays
   * suspended and every note below is a no-op.
   */
  start(): void {
    const ctx = this.#context();
    if (ctx !== null && ctx.state === "suspended") void ctx.resume();
  }

  /**
   * One card moving: a short burst of filtered noise, which is what a card on
   * a table is. The band moves a little every time so that a fast run of moves
   * does not machine-gun.
   */
  move(): void {
    const ctx = this.#context();
    if (ctx === null) return;
    const n = this.#moves++;
    this.#burst({
      cutoff: moveCutoff(n),
      level: MOVE_LEVEL,
      decay: MOVE_DECAY_S,
      at: ctx.currentTime,
      // A different grain of the same noise each time, so it is the sound of a
      // card rather than the sound of a sample.
      offset: (n % 8) * 0.03,
    });
  }

  /** A card reaching its foundation: a soft sine ping, higher the higher the card. */
  home(rank: number): void {
    const ctx = this.#context();
    if (ctx === null) return;
    this.#tone({
      frequency: homeNote(rank),
      level: HOME_LEVEL,
      cutoff: 4000,
      decay: HOME_DECAY_S,
      at: ctx.currentTime,
      type: "sine",
    });
  }

  set muted(muted: boolean) {
    this.#muted = muted;
    const ctx = this.#ctx;
    const master = this.#master;
    if (ctx === null || master === null) return;
    master.gain.cancelScheduledValues(ctx.currentTime);
    master.gain.setTargetAtTime(
      muted ? 0 : MASTER_LEVEL,
      ctx.currentTime,
      MUTE_RAMP_S / 3,
    );
  }

  /** Ascending for Stage 1, descending for Stage 3. */
  arpeggio(descending = false): void {
    const ctx = this.#context();
    if (ctx === null) return;
    const degrees = descending
      ? [...ARPEGGIO_DEGREES].reverse()
      : ARPEGGIO_DEGREES;
    degrees.forEach((degree, i) => {
      this.#tone({
        frequency: scaleNote(degree + PENTATONIC.length),
        level: ARPEGGIO_LEVEL,
        cutoff: 3200,
        decay: 0.9,
        at: ctx.currentTime + i * ARPEGGIO_GAP_S,
        type: "sine",
      });
    });
  }

  /**
   * One bounce. `first` adds the soft sub-bass thump under a card's first
   * contact — heavily low-passed, so it is felt as weight rather than heard as
   * a note.
   */
  bounce(impact: number, progress: number, bounce: number): void {
    const ctx = this.#context();
    if (ctx === null) return;
    const level = bounceLevel(impact);
    this.#tone({
      frequency: bounceNote(progress, bounce),
      level: BOUNCE_LEVEL * level,
      cutoff: bounceCutoff(impact),
      decay: 0.18 + 0.3 * level,
      at: ctx.currentTime,
      type: "triangle",
    });
    if (bounce === 1) {
      this.#tone({
        frequency: 55,
        level: THUMP_LEVEL * level,
        cutoff: 120,
        decay: 0.22,
        at: ctx.currentTime,
        type: "sine",
      });
    }
  }

  /** Let everything ring off over 120ms rather than cutting it dead. */
  release(): void {
    const ctx = this.#ctx;
    if (ctx === null) return;
    const at = ctx.currentTime;
    for (const voice of this.#voices) {
      voice.gain.gain.cancelScheduledValues(at);
      voice.gain.gain.setTargetAtTime(0.0001, at, RELEASE_S / 3);
      voice.stop(at + RELEASE_S);
    }
    this.#voices = [];
  }

  close(): void {
    const ctx = this.#ctx;
    this.#ctx = null;
    this.#master = null;
    this.#noise = null;
    this.#voices = [];
    if (ctx !== null) void ctx.close().catch(() => {});
  }

  #context(): AudioContext | null {
    if (this.#ctx !== null) return this.#ctx;
    if (this.#failed || this.#muted) return null;
    if (typeof AudioContext === "undefined") {
      this.#failed = true;
      return null;
    }
    try {
      const ctx = new AudioContext();
      const master = ctx.createGain();
      master.gain.value = MASTER_LEVEL;
      master.connect(ctx.destination);
      this.#ctx = ctx;
      this.#master = master;
      return ctx;
    } catch {
      // No WebAudio, or the browser refused one. The sequence is still a
      // sequence; it is just a silent one.
      this.#failed = true;
      return null;
    }
  }

  /**
   * One burst of noise through a bandpass through an envelope — the other half
   * of the instrument, and the half that makes an impact rather than a note.
   */
  #burst(spec: {
    cutoff: number;
    level: number;
    decay: number;
    at: number;
    offset: number;
  }): void {
    const ctx = this.#ctx;
    const master = this.#master;
    if (ctx === null || master === null) return;
    this.#reap(spec.at);

    const source = ctx.createBufferSource();
    source.buffer = this.#noiseBuffer(ctx);

    const filter = ctx.createBiquadFilter();
    filter.type = "bandpass";
    filter.frequency.value = spec.cutoff;
    filter.Q.value = 1.2;

    const gain = ctx.createGain();
    gain.gain.setValueAtTime(Math.max(0.0002, spec.level), spec.at);
    gain.gain.exponentialRampToValueAtTime(0.0001, spec.at + spec.decay);

    source.connect(filter).connect(gain).connect(master);
    source.start(spec.at, spec.offset, spec.decay + 0.02);

    const voice: Voice = {
      gain,
      stop: (at) => {
        try {
          source.stop(at);
        } catch {
          // Already stopped. Nothing to do and nothing to report.
        }
      },
    };
    source.addEventListener("ended", () => {
      this.#voices = this.#voices.filter((v) => v !== voice);
    });
    this.#voices.push(voice);
  }

  /** White noise, made once per context and shared by every burst. */
  #noiseBuffer(ctx: AudioContext): AudioBuffer {
    if (this.#noise !== null) return this.#noise;
    const frames = Math.ceil(ctx.sampleRate * NOISE_S);
    const buffer = ctx.createBuffer(1, frames, ctx.sampleRate);
    const channel = buffer.getChannelData(0);
    for (let i = 0; i < frames; i++) channel[i] = Math.random() * 2 - 1;
    this.#noise = buffer;
    return buffer;
  }

  /** One oscillator through one filter through one envelope. That is the whole instrument. */
  #tone(spec: {
    frequency: number;
    level: number;
    cutoff: number;
    decay: number;
    at: number;
    type: OscillatorType;
  }): void {
    const ctx = this.#ctx;
    const master = this.#master;
    if (ctx === null || master === null) return;
    this.#reap(spec.at);

    const osc = ctx.createOscillator();
    osc.type = spec.type;
    osc.frequency.value = spec.frequency;

    const filter = ctx.createBiquadFilter();
    filter.type = "lowpass";
    filter.frequency.value = spec.cutoff;
    filter.Q.value = 0.7;

    const gain = ctx.createGain();
    // 4ms of attack: fast enough to read as a hit, slow enough not to click.
    gain.gain.setValueAtTime(0.0001, spec.at);
    gain.gain.exponentialRampToValueAtTime(
      Math.max(0.0002, spec.level),
      spec.at + 0.004,
    );
    gain.gain.exponentialRampToValueAtTime(0.0001, spec.at + spec.decay);

    osc.connect(filter).connect(gain).connect(master);
    osc.start(spec.at);
    osc.stop(spec.at + spec.decay + 0.05);

    const voice: Voice = {
      gain,
      stop: (at) => {
        try {
          osc.stop(at);
        } catch {
          // Already stopped. Nothing to do and nothing to report.
        }
      },
    };
    osc.addEventListener("ended", () => {
      this.#voices = this.#voices.filter((v) => v !== voice);
    });
    this.#voices.push(voice);
  }

  /** Voice cap, oldest stolen. */
  #reap(now: number): void {
    while (this.#voices.length >= VOICE_CAP) {
      const oldest = this.#voices.shift();
      if (oldest === undefined) return;
      oldest.gain.gain.cancelScheduledValues(now);
      oldest.gain.gain.setTargetAtTime(0.0001, now, 0.01);
      oldest.stop(now + 0.04);
    }
  }
}
