import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";

import {
  EMPTY_POOL,
  type Pool,
  Pools,
  decodePool,
  newSeed,
} from "../../src/game/pool.ts";

/**
 * The pools are the one piece of shipped *data* the game depends on, and two
 * of their properties are promises rather than conveniences: that the daily
 * deal is the same deal for everyone on a given date, forever, and that a
 * missing pool is a playable game rather than a broken one.
 */

function poolOf(seeds: readonly number[]): Pool {
  return Uint32Array.from(seeds);
}

function packed(seeds: readonly number[]): ArrayBuffer {
  const bytes = new Uint8Array(seeds.length * 4);
  const view = new DataView(bytes.buffer);
  seeds.forEach((seed, index) => view.setUint32(index * 4, seed, true));
  return bytes.buffer;
}

describe("decoding a pool", () => {
  it("reads deal numbers little-endian, whatever the machine prefers", () => {
    assert.deepEqual(
      [...decodePool(packed([0, 1, 4_294_967_295]))],
      [0, 1, 4_294_967_295],
    );
  });

  it("ignores a trailing partial entry rather than inventing a deal", () => {
    const bytes = new Uint8Array(6);
    new DataView(bytes.buffer).setUint32(0, 7, true);
    assert.deepEqual([...decodePool(bytes.buffer)], [7]);
  });

  it("is empty for an empty file", () => {
    assert.equal(decodePool(new ArrayBuffer(0)).length, 0);
  });
});

describe("picking a new deal", () => {
  it("comes out of the pool, when there is one", () => {
    const pool = poolOf([11, 22, 33, 44]);
    assert.equal(
      newSeed(pool, () => 0),
      11,
    );
    assert.equal(
      newSeed(pool, () => 0.99),
      44,
    );
    assert.equal(
      newSeed(pool, () => 0.5),
      33,
    );
  });

  /**
   * Winnable-only off, and also the first deal of a load that beat the fetch.
   * Both are the same code path on purpose: there is no state in which the
   * game cannot deal.
   */
  it("comes out of the whole seed space when there is no pool", () => {
    assert.equal(
      newSeed(EMPTY_POOL, () => 0),
      0,
    );
    assert.equal(
      newSeed(EMPTY_POOL, () => 0.999999999),
      4_294_967_291,
    );
    const seed = newSeed(EMPTY_POOL);
    assert.ok(Number.isInteger(seed) && seed >= 0 && seed <= 4_294_967_295);
  });
});

/**
 * The fetch, which is the one thing in the product that goes to the network
 * after load — and the one thing nothing waits for. Every failure it can have
 * is the same failure: no pool, deals from the whole seed space, a game that
 * is slightly harder and not at all broken.
 */
describe("loading a pool", () => {
  async function withFetch<T>(
    stub: typeof globalThis.fetch,
    run: (pools: Pools) => Promise<T>,
  ): Promise<T> {
    const real = globalThis.fetch;
    globalThis.fetch = stub;
    try {
      return await run(new Pools());
    } finally {
      globalThis.fetch = real;
    }
  }

  const bytes = (seeds: readonly number[]): ArrayBuffer => {
    const out = new Uint8Array(seeds.length * 4);
    const view = new DataView(out.buffer);
    seeds.forEach((seed, index) => view.setUint32(index * 4, seed, true));
    return out.buffer;
  };

  it("decodes what it fetched, and remembers it", async () => {
    let calls = 0;
    await withFetch(
      async () => {
        calls++;
        return new Response(bytes([4, 8, 15]));
      },
      async (pools) => {
        assert.deepEqual([...pools.get(1)], [], "empty before it lands");
        assert.deepEqual([...(await pools.load(1))], [4, 8, 15]);
        assert.deepEqual([...pools.get(1)], [4, 8, 15]);

        // One fetch per draw mode per page load, however often it is asked for.
        await pools.load(1);
        assert.equal(calls, 1);
      },
    );
  });

  it("is an empty pool when the network says no", async () => {
    await withFetch(
      async () => {
        throw new Error("offline");
      },
      async (pools) => {
        assert.deepEqual([...(await pools.load(3))], []);
        assert.deepEqual([...pools.get(3)], []);
      },
    );
  });

  it("is an empty pool when the server says no", async () => {
    await withFetch(
      async () => new Response("not here", { status: 404 }),
      async (pools) => {
        assert.deepEqual([...(await pools.load(1))], []);
      },
    );
  });

  it("keeps the two draw modes apart", async () => {
    await withFetch(
      async (input) => {
        const url = String(input);
        return new Response(bytes(url.includes("winnable-3") ? [3] : [1]));
      },
      async (pools) => {
        assert.deepEqual([...(await pools.load(1))], [1]);
        assert.deepEqual([...(await pools.load(3))], [3]);
      },
    );
  });
});

/**
 * The files as committed. These are generated by
 * `node scripts/generate-winnable.ts`, which takes a machine-hour and is run
 * by hand; what a test can check is that what's in the repo is sorted, because the
 * pool is append-only. Whether the seeds are *really* winnable is
 * test/engine/solve.test.ts, which re-solves a sample of them.
 */
describe("the committed pools", () => {
  for (const drawCount of [1, 3] as const) {
    it(`draw-${drawCount}: is sorted and has no repeats`, () => {
      const pool = readPool(drawCount);
      assert.ok(pool.length > 0);
      for (let index = 1; index < pool.length; index++) {
        assert.ok(
          (pool[index] as number) > (pool[index - 1] as number),
          `entry ${index} is out of order`,
        );
      }
    });
  }
});

function readPool(drawCount: 1 | 3): Pool {
  const bytes = readFileSync(
    new URL(`../../src/data/winnable-${drawCount}.bin`, import.meta.url),
  );
  return decodePool(
    bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength),
  );
}
